# # # # # # # #
#   K i k o   #
# # # # # # # #

gems:
    - "jekyll-gallery-generator"

# Basic
name:               "shawa"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "/about"
  - name:           "Projects"
    href:           "/projects"


# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"


gallery:
  title: "photos"
  title_prefix: ""
